

# Dataset Stuff ---------------------------------------------
#
data_path: ../../data
# output_path: ../../output
model_folder: ../models
model_name: model_02-18-20_03:24:31.joblib

# OCR configs -----------------------------------------------
# number of threads to run OCR process. Increase to speed up OCR.
num_cores: 16

# word processing configs -----------------------------------
language: 'english'
num_pages: 2
text_folder_path: ../../data/preprocessed/complaints

# Classifier parameters -------------------------------------
county_names : ['fresno', 'kern', 'los angeles', 'santa clara', 'san francisco', 'san mateo']
keys : ['FRE', 'KC', 'LA', 'SCL', 'SFC', 'SM']
# 3000 counties in the states
# good balance between speed and performance
num_features: 10000
test_ratio: 0.2

# Inference parameters --------------------------------------
# list of ids to run on prediction.
ids: ["CA_FRE_09iRh_XfvepbPbJreq6wcQ2", "CA_FRE_0BvgNMShVWXTMrvCogDYbA2", "CA_SCL_4gLMQ6Og9STw4lawaORElw2"]

# inference on pdf files from a folder
pdf_classification_path: ../dummy_data/
processed_text_path: ../dummy_data/processed